// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jsdtonjkqrlamwgtammd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpzZHRvbmprcXJsYW13Z3RhbW1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MDM0ODEsImV4cCI6MjA2OTE3OTQ4MX0.t_g9lEEZCg9uzbsGu8eBVP6i5vCwOy-zh7_ewoOK4GE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});